### below command to patch from cmd 
### kubectl patch svc argocd-server -n argocd --type=json -p "[{\"op\": \"replace\", \"path\": \"/spec/type\", \"value\": \"NodePort\"}]"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-deployment
  labels:
    app: confluence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confluence
  template:
    metadata:
      labels:
        app: confluence
    spec:
      containers:
      - name: confluence
        image: atlassian/confluence: 8.5.16
        ports:
        - containerPort: 80
        - containerPort: 8090
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: confluence-service
  labels:
    app:  confluence
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8090
    nodePort: 32001
    protocol: TCP
  selector:
    app: confluence